/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.employeeManagementSystem.MainAdminPage;

import com.employeeManagementSystem.app.LoginPage;
import com.employeeManagementSystem.db_connection.DBConnection;
import static com.employeeManagementSystem.secutiry.EncryptDecrypt.encrypt;
import java.awt.Color;
import java.awt.Image;
import java.io.InputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mydeen
 */
public class EmployeePage extends javax.swing.JFrame {

    /**
     * Creates new form EmployeePage
     */
    private String userName;
    
    public EmployeePage() {
        initComponents();
    }
    
    public EmployeePage(String employeeName) {
        initComponents();
        lbl_welcomeEmployee.setText("Welcome, " + employeeName + " !"); 
        lbl_welcomeEmp.setText("Welcome, " + employeeName ); 
        userName = employeeName;
        loadLeaveData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();
        lbl_welcomeEmployee = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        panel_dashboard = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panel_employees = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panel_leaves = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        panel_salary = new javax.swing.JPanel();
        icon_salary = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        panel_settings = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tab1 = new javax.swing.JPanel();
        panel_dash = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        lbl_welcomeEmp = new javax.swing.JLabel();
        emp_name = new javax.swing.JLabel();
        tab2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        lbl_fetchname = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        lbl_fetchEmpID = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        lbl_fetchDOB = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        lbl_fetchGender = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        lbl_fetchDepartment = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        lbl_fetchMaritalStatus = new javax.swing.JLabel();
        lbl_profilePicture = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        tab4 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        btn_addLeave = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_leave = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cb_leaveType = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        dp_fromDate = new com.toedter.calendar.JDateChooser();
        jLabel21 = new javax.swing.JLabel();
        dp_toDate = new com.toedter.calendar.JDateChooser();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_description = new javax.swing.JTextArea();
        btn_add_leave = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        btn_back = new javax.swing.JButton();
        tab5 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_salary = new javax.swing.JTable();
        jSeparator4 = new javax.swing.JSeparator();
        tab6 = new javax.swing.JPanel();
        jPanel35 = new javax.swing.JPanel();
        jPanel36 = new javax.swing.JPanel();
        pwd_conpass = new javax.swing.JPasswordField();
        btn_clear = new javax.swing.JButton();
        btn_submit = new javax.swing.JButton();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        pwd_newpass = new javax.swing.JPasswordField();
        lbl_message = new javax.swing.JLabel();
        txtCurrentUserName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(150, 100, 0, 0));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setMinimumSize(new java.awt.Dimension(1200, 50));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Pristina", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Employee Management System");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btn_logout.setBackground(new java.awt.Color(0, 204, 204));
        btn_logout.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setText("LOGOUT");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        jPanel2.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 20, -1, -1));

        lbl_welcomeEmployee.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lbl_welcomeEmployee.setForeground(new java.awt.Color(255, 255, 255));
        lbl_welcomeEmployee.setText("Welcome,");
        jPanel2.add(lbl_welcomeEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 280, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1249, 60));

        jPanel3.setBackground(new java.awt.Color(4, 66, 66));

        panel_dashboard.setBackground(new java.awt.Color(4, 66, 66));
        panel_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_dashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_dashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_dashboardMouseExited(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mydeen\\Desktop\\-\\Employee_Management_System\\Images\\dashboard.png")); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel3.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Dashboard");

        javax.swing.GroupLayout panel_dashboardLayout = new javax.swing.GroupLayout(panel_dashboard);
        panel_dashboard.setLayout(panel_dashboardLayout);
        panel_dashboardLayout.setHorizontalGroup(
            panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dashboardLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        panel_dashboardLayout.setVerticalGroup(
            panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_dashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        panel_employees.setBackground(new java.awt.Color(4, 66, 66));
        panel_employees.setPreferredSize(new java.awt.Dimension(180, 42));
        panel_employees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_employeesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_employeesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_employeesMouseExited(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mydeen\\Desktop\\-\\Employee_Management_System\\Images\\employees.png")); // NOI18N
        jLabel5.setPreferredSize(new java.awt.Dimension(72, 30));

        jLabel6.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("My Profile");
        jLabel6.setPreferredSize(new java.awt.Dimension(82, 22));

        javax.swing.GroupLayout panel_employeesLayout = new javax.swing.GroupLayout(panel_employees);
        panel_employees.setLayout(panel_employeesLayout);
        panel_employeesLayout.setHorizontalGroup(
            panel_employeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_employeesLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        panel_employeesLayout.setVerticalGroup(
            panel_employeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_employeesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_employeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        panel_leaves.setBackground(new java.awt.Color(4, 66, 66));
        panel_leaves.setPreferredSize(new java.awt.Dimension(180, 42));
        panel_leaves.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_leavesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_leavesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_leavesMouseExited(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mydeen\\Desktop\\-\\Employee_Management_System\\Images\\leaves.png")); // NOI18N

        jLabel10.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Leaves");

        javax.swing.GroupLayout panel_leavesLayout = new javax.swing.GroupLayout(panel_leaves);
        panel_leaves.setLayout(panel_leavesLayout);
        panel_leavesLayout.setHorizontalGroup(
            panel_leavesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_leavesLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_leavesLayout.setVerticalGroup(
            panel_leavesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_leavesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_leavesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panel_salary.setBackground(new java.awt.Color(4, 66, 66));
        panel_salary.setPreferredSize(new java.awt.Dimension(180, 42));
        panel_salary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_salaryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_salaryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_salaryMouseExited(evt);
            }
        });

        icon_salary.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mydeen\\Desktop\\-\\Employee_Management_System\\Images\\salary.png")); // NOI18N

        jLabel12.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Salary");

        javax.swing.GroupLayout panel_salaryLayout = new javax.swing.GroupLayout(panel_salary);
        panel_salary.setLayout(panel_salaryLayout);
        panel_salaryLayout.setHorizontalGroup(
            panel_salaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_salaryLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(icon_salary, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_salaryLayout.setVerticalGroup(
            panel_salaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_salaryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_salaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icon_salary, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panel_settings.setBackground(new java.awt.Color(4, 66, 66));
        panel_settings.setPreferredSize(new java.awt.Dimension(180, 42));
        panel_settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_settingsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_settingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_settingsMouseExited(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mydeen\\Desktop\\-\\Employee_Management_System\\Images\\settings.png")); // NOI18N

        jLabel14.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Settings");

        javax.swing.GroupLayout panel_settingsLayout = new javax.swing.GroupLayout(panel_settings);
        panel_settings.setLayout(panel_settingsLayout);
        panel_settingsLayout.setHorizontalGroup(
            panel_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_settingsLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        panel_settingsLayout.setVerticalGroup(
            panel_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_settingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panel_dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_employees, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(panel_leaves, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(panel_salary, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                .addGap(25, 25, 25))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(panel_settings, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(panel_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(panel_employees, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panel_leaves, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panel_salary, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_settings, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(268, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 240, 640));

        jTabbedPane1.setBackground(new java.awt.Color(204, 255, 0));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 0));
        jLabel2.setText("Dashboard Overview");

        jPanel30.setBackground(new java.awt.Color(0, 153, 153));

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/employeeManagementSystem/Images/employees.png"))); // NOI18N

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel30Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel30Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel53, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        lbl_welcomeEmp.setFont(new java.awt.Font("Perpetua", 2, 36)); // NOI18N
        lbl_welcomeEmp.setText("Welcome Back, ");

        emp_name.setFont(new java.awt.Font("Perpetua", 2, 36)); // NOI18N

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addComponent(jPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_welcomeEmp)
                .addGap(18, 18, 18)
                .addComponent(emp_name, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 367, Short.MAX_VALUE))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel24Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_welcomeEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emp_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout panel_dashLayout = new javax.swing.GroupLayout(panel_dash);
        panel_dash.setLayout(panel_dashLayout);
        panel_dashLayout.setHorizontalGroup(
            panel_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dashLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(panel_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        panel_dashLayout.setVerticalGroup(
            panel_dashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dashLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(455, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tab1Layout = new javax.swing.GroupLayout(tab1);
        tab1.setLayout(tab1Layout);
        tab1Layout.setHorizontalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_dash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tab1Layout.setVerticalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab1Layout.createSequentialGroup()
                .addGap(0, 65, Short.MAX_VALUE)
                .addComponent(panel_dash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("tab1", tab1);

        tab2.setBackground(new java.awt.Color(254, 254, 254));

        jPanel6.setBackground(new java.awt.Color(243, 243, 243));

        jPanel27.setBackground(new java.awt.Color(255, 255, 255));

        jLabel45.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 204, 0));
        jLabel45.setText("Employee Details");

        jLabel46.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(0, 153, 153));
        jLabel46.setText("Name : ");

        lbl_fetchname.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel48.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(0, 153, 153));
        jLabel48.setText("Employee ID : ");

        lbl_fetchEmpID.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel50.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(0, 153, 153));
        jLabel50.setText("Date of Birth : ");

        lbl_fetchDOB.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel52.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(0, 153, 153));
        jLabel52.setText("Gender : ");

        lbl_fetchGender.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel54.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(0, 153, 153));
        jLabel54.setText("Department : ");

        lbl_fetchDepartment.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel56.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(0, 153, 153));
        jLabel56.setText("Marital Status : ");

        lbl_fetchMaritalStatus.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel27Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lbl_profilePicture, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel27Layout.createSequentialGroup()
                        .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_fetchMaritalStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel27Layout.createSequentialGroup()
                        .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(lbl_fetchDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel27Layout.createSequentialGroup()
                        .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(lbl_fetchGender, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel27Layout.createSequentialGroup()
                        .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(lbl_fetchname, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel27Layout.createSequentialGroup()
                        .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel48, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(jLabel50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_fetchDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_fetchEmpID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(36, 36, 36))
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addComponent(jLabel45)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel27Layout.createSequentialGroup()
                        .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_fetchname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel46, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_fetchEmpID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_fetchDOB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_fetchGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_fetchDepartment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_fetchMaritalStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbl_profilePicture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tab2Layout = new javax.swing.GroupLayout(tab2);
        tab2.setLayout(tab2Layout);
        tab2Layout.setHorizontalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tab2Layout.setVerticalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab2Layout.createSequentialGroup()
                .addGap(0, 64, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("tab2", tab2);

        tab4.setBackground(new java.awt.Color(254, 254, 254));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 204, 0));
        jLabel16.setText("Manage Leaves");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 180, 30));

        btn_addLeave.setBackground(new java.awt.Color(0, 153, 153));
        btn_addLeave.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_addLeave.setForeground(new java.awt.Color(255, 255, 255));
        btn_addLeave.setText("Add Leave");
        btn_addLeave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addLeaveActionPerformed(evt);
            }
        });
        jPanel4.add(btn_addLeave, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 170, 150, 30));

        tbl_leave.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tbl_leave.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sno", "Leave Type", "From Date", "To Date", "Description", "Applied Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_leave.setRowHeight(40);
        jScrollPane3.setViewportView(tbl_leave);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 900, 370));
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1010, 10));

        jTabbedPane2.addTab("tab1", jPanel4);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setBackground(new java.awt.Color(255, 204, 0));
        jLabel18.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 204, 0));
        jLabel18.setText("Request for Leave");

        jLabel19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 153, 153));
        jLabel19.setText("Leave Type");

        cb_leaveType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please select the leave type", "Casual Leave", "Sick Leave", "Annual Leave", "Unpaid Leave", "Emergency Leave" }));

        jLabel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 153, 153));
        jLabel20.setText("From Date");

        jLabel21.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 153, 153));
        jLabel21.setText("To Date");

        jLabel22.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 153, 153));
        jLabel22.setText("Description");

        txt_description.setColumns(20);
        txt_description.setRows(5);
        jScrollPane4.setViewportView(txt_description);

        btn_add_leave.setBackground(new java.awt.Color(0, 153, 153));
        btn_add_leave.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_add_leave.setForeground(new java.awt.Color(255, 255, 255));
        btn_add_leave.setText("ADD LEAVE");
        btn_add_leave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_leaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dp_fromDate, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 392, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dp_toDate, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(130, 130, 130))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cb_leaveType, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE)
                            .addComponent(btn_add_leave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(115, 115, 115))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator3))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(cb_leaveType, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dp_toDate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dp_fromDate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btn_add_leave, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        btn_back.setBackground(new java.awt.Color(0, 153, 153));
        btn_back.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setText("BACK");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_back)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        jTabbedPane2.addTab("tab2", jPanel5);

        javax.swing.GroupLayout tab4Layout = new javax.swing.GroupLayout(tab4);
        tab4.setLayout(tab4Layout);
        tab4Layout.setHorizontalGroup(
            tab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        tab4Layout.setVerticalGroup(
            tab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("tab4", tab4);

        tab5.setBackground(new java.awt.Color(245, 245, 245));

        jLabel23.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 204, 0));
        jLabel23.setText("Salary History");

        tbl_salary.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tbl_salary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Salary ID", "Employee Name", "Basic Salary ", "Monthly Allowance ", "Deduction", "NetPay", "Pay Date "
            }
        ));
        tbl_salary.setRowHeight(40);
        jScrollPane1.setViewportView(tbl_salary);

        javax.swing.GroupLayout tab5Layout = new javax.swing.GroupLayout(tab5);
        tab5.setLayout(tab5Layout);
        tab5Layout.setHorizontalGroup(
            tab5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab5Layout.createSequentialGroup()
                .addGroup(tab5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab5Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 887, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tab5Layout.createSequentialGroup()
                        .addGap(425, 425, 425)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        tab5Layout.setVerticalGroup(
            tab5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab5Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab5", tab5);

        tab6.setBackground(new java.awt.Color(245, 245, 245));

        jPanel36.setBackground(new java.awt.Color(255, 255, 255));

        pwd_conpass.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        pwd_conpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwd_conpassActionPerformed(evt);
            }
        });

        btn_clear.setBackground(new java.awt.Color(0, 204, 204));
        btn_clear.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        btn_clear.setForeground(new java.awt.Color(255, 255, 255));
        btn_clear.setText("CLEAR");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_submit.setBackground(new java.awt.Color(0, 204, 204));
        btn_submit.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        btn_submit.setForeground(new java.awt.Color(255, 255, 255));
        btn_submit.setText("SUBMIT");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });

        jLabel78.setBackground(new java.awt.Color(255, 255, 255));
        jLabel78.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel78.setForeground(new java.awt.Color(0, 153, 153));
        jLabel78.setText("Current Username");

        jLabel79.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(0, 153, 153));
        jLabel79.setText("New password");

        jLabel80.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(0, 153, 153));
        jLabel80.setText("Confirm Password");

        pwd_newpass.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        pwd_newpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwd_newpassActionPerformed(evt);
            }
        });

        lbl_message.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        lbl_message.setForeground(new java.awt.Color(255, 0, 51));

        txtCurrentUserName.setEditable(false);
        txtCurrentUserName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel36Layout = new javax.swing.GroupLayout(jPanel36);
        jPanel36.setLayout(jPanel36Layout);
        jPanel36Layout.setHorizontalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel36Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pwd_newpass)
                    .addComponent(jLabel80)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel36Layout.createSequentialGroup()
                        .addComponent(btn_clear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                        .addComponent(btn_submit))
                    .addComponent(jLabel79, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel78, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwd_conpass)
                    .addComponent(lbl_message, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCurrentUserName))
                .addGap(0, 45, Short.MAX_VALUE))
        );
        jPanel36Layout.setVerticalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel36Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel78)
                .addGap(18, 18, 18)
                .addComponent(txtCurrentUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel79)
                .addGap(19, 19, 19)
                .addComponent(pwd_newpass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel80)
                .addGap(18, 18, 18)
                .addComponent(pwd_conpass, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(lbl_message, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_clear)
                    .addComponent(btn_submit))
                .addGap(48, 48, 48))
        );

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 204, 0));
        jLabel7.setText("Change Password");

        javax.swing.GroupLayout jPanel35Layout = new javax.swing.GroupLayout(jPanel35);
        jPanel35.setLayout(jPanel35Layout);
        jPanel35Layout.setHorizontalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel35Layout.createSequentialGroup()
                .addGroup(jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel35Layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(jPanel36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel35Layout.createSequentialGroup()
                        .addGap(385, 385, 385)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(323, Short.MAX_VALUE))
            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel35Layout.setVerticalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel35Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jPanel36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout tab6Layout = new javax.swing.GroupLayout(tab6);
        tab6.setLayout(tab6Layout);
        tab6Layout.setHorizontalGroup(
            tab6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tab6Layout.setVerticalGroup(
            tab6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab6Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jPanel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab6", tab6);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, -40, 1010, 740));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        LoginPage lp = new LoginPage();
        this.dispose();
        lp.setVisible(true);
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void panel_dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_dashboardMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_panel_dashboardMouseClicked

    private void panel_dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_dashboardMouseEntered
        // TODO add your handling code here:
        panel_dashboard.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_panel_dashboardMouseEntered

    private void panel_dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_dashboardMouseExited
        // TODO add your handling code here:
        panel_dashboard.setBackground(new Color(4,66,66));
    }//GEN-LAST:event_panel_dashboardMouseExited

    private void panel_employeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_employeesMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
        openProfile(); 
    }//GEN-LAST:event_panel_employeesMouseClicked

    private void panel_employeesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_employeesMouseEntered
        // TODO add your handling code here:
        panel_employees.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_panel_employeesMouseEntered

    private void panel_employeesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_employeesMouseExited
        // TODO add your handling code here:
        panel_employees.setBackground(new Color(4,66,66));
    }//GEN-LAST:event_panel_employeesMouseExited

    private void panel_leavesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_leavesMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_panel_leavesMouseClicked

    private void panel_leavesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_leavesMouseEntered
        // TODO add your handling code here:
        panel_leaves.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_panel_leavesMouseEntered

    private void panel_leavesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_leavesMouseExited
        // TODO add your handling code here:
        panel_leaves.setBackground(new Color(4,66,66));
    }//GEN-LAST:event_panel_leavesMouseExited

    private void panel_salaryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_salaryMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
        String fullName = lbl_welcomeEmp.getText().trim();
        String employeeName = fullName.replace("Welcome, ", "").trim();
        fetchAndDisplaySalaryDetails(employeeName); 
    }//GEN-LAST:event_panel_salaryMouseClicked
    
    private void fetchAndDisplaySalaryDetails(String employeeName) {
        // Define the SQL query to fetch salary details
        String sql = "SELECT SalaryID, EmployeeName, BasicSalary, MonthlyAllowance, Deduction, NetPay, PayDate FROM Salary_Tbl WHERE EmployeeName = ?";

        // Create a table model for displaying data
        DefaultTableModel tableModel = (DefaultTableModel) tbl_salary.getModel(); // Get the existing model of the table
        tableModel.setRowCount(0); // Clear the existing rows in the table before adding new ones

        try (Connection conn = DBConnection.getConnection(); PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setString(1, employeeName); // Set the employee name parameter
            try (ResultSet rs = stmt.executeQuery()) {
                // Populate the table with data from the result set
                while (rs.next()) {
                    Object[] row = {
                        rs.getInt("SalaryID"),
                        rs.getString("EmployeeName"),
                        rs.getDouble("BasicSalary"),
                        rs.getDouble("MonthlyAllowance"),
                        rs.getDouble("Deduction"),
                        rs.getDouble("NetPay"),
                        rs.getDate("PayDate")
                    };
                    tableModel.addRow(row);
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error fetching salary details.", "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void panel_salaryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_salaryMouseEntered
        // TODO add your handling code here:
        panel_salary.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_panel_salaryMouseEntered
    
    

    
    private void panel_salaryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_salaryMouseExited
        // TODO add your handling code here:
        panel_salary.setBackground(new Color(4,66,66));
    }//GEN-LAST:event_panel_salaryMouseExited

    private void panel_settingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_settingsMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(4);
        txtCurrentUserName.setText(userName);
    }//GEN-LAST:event_panel_settingsMouseClicked

    private void panel_settingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_settingsMouseEntered
        // TODO add your handling code here:
        panel_settings.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_panel_settingsMouseEntered

    private void panel_settingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_settingsMouseExited
        // TODO add your handling code here:
        panel_settings.setBackground(new Color(4,66,66));
    }//GEN-LAST:event_panel_settingsMouseExited

    private void btn_addLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addLeaveActionPerformed
        // TODO add your handling code here:
        jTabbedPane2.setSelectedIndex(1);
    }//GEN-LAST:event_btn_addLeaveActionPerformed

    private void btn_add_leaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_leaveActionPerformed
        // TODO add your handling code here:
        addLeaveRequest();
    }//GEN-LAST:event_btn_add_leaveActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        jTabbedPane2.setSelectedIndex(0);
    }//GEN-LAST:event_btn_backActionPerformed

    private void pwd_conpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwd_conpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwd_conpassActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        pwd_newpass.setText("");
        pwd_conpass.setText("");
        lbl_message.setText("");
    }//GEN-LAST:event_btn_clearActionPerformed
        
    private void updatePassword() throws Exception {
        String newPassword = new String(pwd_newpass.getPassword());
        String confirmPassword = new String(pwd_conpass.getPassword());

        // Validate input
        if (newPassword.isEmpty() || confirmPassword.isEmpty()) {
            lbl_message.setForeground(Color.RED);
            lbl_message.setText("Please enter a new password and confirm it.");
            return;
        }

        if (!newPassword.equals(confirmPassword)) {
            lbl_message.setForeground(Color.RED);
            lbl_message.setText("Passwords do not match. Please try again.");
            return;
        }

        // Update password in the database
        String query = "UPDATE Employee_Tbl SET Password = ? WHERE Name = ?";

        try (Connection connection = DBConnection.getConnection(); PreparedStatement preparedStatement = connection.prepareStatement(query)) {

            // Uncomment the following line if you want to test without encryption
            // preparedStatement.setString(1, newPassword);
            // Encrypt and set the new password
            preparedStatement.setString(1, encrypt(newPassword));
            preparedStatement.setString(2, userName);

            int rowsAffected = preparedStatement.executeUpdate();

            if (rowsAffected > 0) {
                lbl_message.setForeground(Color.GREEN);
                lbl_message.setText("Successfully updated the password.");
                pwd_newpass.setText("");
                pwd_conpass.setText("");
            } else {
                lbl_message.setForeground(Color.RED);
                lbl_message.setText("Error updating password. Please try again.");
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
            lbl_message.setText("Database error. Please try again later.");
        } catch (Exception ex) {
            ex.printStackTrace();
            lbl_message.setText("Unexpected error. Please try again later.");
        }
    }
        
    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        try {
            updatePassword();
        } catch (Exception ex) {
            ex.printStackTrace();
            lbl_message.setText("Unexpected error while updating password.");
        }
    }//GEN-LAST:event_btn_submitActionPerformed

    private void pwd_newpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwd_newpassActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_pwd_newpassActionPerformed

private void openProfile() {
    String fullName = lbl_welcomeEmp.getText().trim();
    String employeeName = fullName.replace("Welcome, ", "").trim();

    // Debug print: what is the employee name being fetched?
    System.out.println("Employee Name to Fetch: '" + employeeName + "'"); 

    int employeeID = fetchEmployeeID(employeeName);
    if (employeeID != -1) {
        displayEmployeeDetails(employeeID);
    } else {
        JOptionPane.showMessageDialog(this, "Employee not found: " + employeeName, "Error", JOptionPane.ERROR_MESSAGE);
    }
}

private int fetchEmployeeID(String employeeName) {
    Connection conn = DBConnection.getConnection();
    String query = "SELECT EmployeeID FROM Employee_Tbl WHERE LOWER(TRIM(Name)) = LOWER(TRIM(?))"; // Case insensitive and trimmed
    int employeeID = -1; // Default value if not found

    try (PreparedStatement pstmt = conn.prepareStatement(query)) {
        pstmt.setString(1, employeeName);
        System.out.println("SQL Query: " + pstmt.toString()); // Print the SQL statement for debugging

        ResultSet resultSet = pstmt.executeQuery();

        // Debug print: Check if any results were returned
        if (resultSet.next()) {
            employeeID = resultSet.getInt("EmployeeID"); // Retrieve the employee ID
            System.out.println("Found Employee ID: " + employeeID); // Debug print
        } else {
            System.out.println("No Employee found for name: " + employeeName); // Debug print
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error retrieving employee ID.", "Error", JOptionPane.ERROR_MESSAGE);
    }

    return employeeID; // Return the found employee ID
}

    
    private void displayEmployeeDetails(int employeeID) {
        Connection conn = DBConnection.getConnection();
        String query = "SELECT Name, EmployeeID, DateOfBirth, Gender, Department, MarriedStatus, EmployeeImage FROM Employee_Tbl WHERE EmployeeID = ?";

        try (PreparedStatement pstmt = conn.prepareStatement(query)) {
            pstmt.setInt(1, employeeID);
            ResultSet resultSet = pstmt.executeQuery();

            if (resultSet.next()) {
                // Set textual details
                lbl_fetchname.setText(resultSet.getString("Name"));
                lbl_fetchEmpID.setText(String.valueOf(resultSet.getInt("EmployeeID")));
                lbl_fetchDOB.setText(resultSet.getString("DateOfBirth"));
                lbl_fetchGender.setText(resultSet.getString("Gender"));
                lbl_fetchDepartment.setText(resultSet.getString("Department"));
                lbl_fetchMaritalStatus.setText(resultSet.getString("MarriedStatus"));

                // Retrieve and set the employee image
                Blob imageBlob = resultSet.getBlob("EmployeeImage");
                if (imageBlob != null) {
                    InputStream inputStream = imageBlob.getBinaryStream();
                    Image img = ImageIO.read(inputStream);
                    ImageIcon icon = new ImageIcon(img.getScaledInstance(lbl_profilePicture.getWidth(), lbl_profilePicture.getHeight(), Image.SCALE_SMOOTH));
                    lbl_profilePicture.setIcon(icon);
                } else {
                    lbl_profilePicture.setIcon(null); // or set a default icon
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading employee details.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void addLeaveRequest() {
    // Get values from UI components
    String leaveType = cb_leaveType.getSelectedItem().toString(); // Assuming cb_leaveType is a JComboBox for leave types
    java.util.Date fromDate = dp_fromDate.getDate(); // Assuming dp_fromDate is a date picker component
    java.util.Date toDate = dp_toDate.getDate();     // Assuming dp_toDate is a date picker component
    String description = txt_description.getText();  // Assuming txt_description is a JTextArea for description
    java.sql.Date appliedDate = new java.sql.Date(System.currentTimeMillis()); // Set current date as applied date
    String username = userName; // Assuming you store the username of the logged-in employee

    // Validation: Check if required fields are filled and dates are valid
    if (leaveType.isEmpty() || fromDate == null || toDate == null || description.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please fill all required fields.");
        return;
    }

    if (fromDate.after(toDate)) {
        JOptionPane.showMessageDialog(null, "From Date cannot be after To Date.");
        return;
    }

    // Database connection and insertion
    try (Connection conn = DBConnection.getConnection()) {
        // Prepare SQL statement (fixed: using Username instead of employeeEmail)
        String sql = "INSERT INTO Leave_Tbl (Leave_Type, From_Date, To_Date, Description, Applied_Date, Status, Username) VALUES (?, ?, ?, ?, ?, ?, ?)";

        PreparedStatement pstmt = conn.prepareStatement(sql);

        // Set values in the SQL statement
        pstmt.setString(1, leaveType);
        pstmt.setDate(2, new java.sql.Date(fromDate.getTime()));
        pstmt.setDate(3, new java.sql.Date(toDate.getTime()));
        pstmt.setString(4, description);
        pstmt.setDate(5, appliedDate);
        pstmt.setString(6, "Pending");
        pstmt.setString(7, username); // Use username here

        // Execute insertion and show success/failure message
        int rowsAffected = pstmt.executeUpdate();
        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(null, "Leave request submitted successfully!");
            
            loadLeaveData(); // for refresh

            // Clear all fields after successful submission
            cb_leaveType.setSelectedIndex(0); // Reset to the first option in the combo box
            dp_fromDate.setDate(null);        // Clear the date picker for From Date
            dp_toDate.setDate(null);          // Clear the date picker for To Date
            txt_description.setText("");      // Clear the description text area
        } else {
            JOptionPane.showMessageDialog(null, "Failed to submit leave request. Please try again.");
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Database error: " + e.getMessage());
        e.printStackTrace();
    }
}




private void loadLeaveData() {
    // Assuming you have a table to display leave data
    // Example: JTable leaveTable
    String username = userName;
    String query = "SELECT Sno, Leave_Type, From_Date, To_Date, Description, Applied_Date, Status FROM Leave_Tbl WHERE Username = ? ORDER BY Applied_Date DESC";

    try (Connection conn = DBConnection.getConnection()) {
        if (conn == null) {
            JOptionPane.showMessageDialog(this, "Failed to connect to the database.", "Connection Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Prepare SQL query with EmployeeEmail as the filter
        try (PreparedStatement pst = conn.prepareStatement(query)) {
            pst.setString(1, username);  // Assuming this.employeeEmail contains the logged-in employee's email

            try (ResultSet rs = pst.executeQuery()) {
                // Clear previous data from the table (if any)
                DefaultTableModel model = (DefaultTableModel) tbl_leave.getModel();
                model.setRowCount(0);  // Clears the table

                // Iterate over the result set and populate the table
                while (rs.next()) {
                    int sno = rs.getInt("Sno"); // Get Sno from the result set
                    String leaveType = rs.getString("Leave_Type");
                    Date fromDate = rs.getDate("From_Date");
                    Date toDate = rs.getDate("To_Date");
                    String description = rs.getString("Description");
                    Date appliedDate = rs.getDate("Applied_Date");
                    String status = rs.getString("Status");

                    // Add the row to the table
                    model.addRow(new Object[]{
                        sno,                       // Add the Sno in the first column
                        leaveType,
                        fromDate.toString(),       // Convert Date to String if needed
                        toDate.toString(),
                        description,
                        appliedDate.toString(),
                        status
                    });
                }
            }
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
    }
}




  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addLeave;
    private javax.swing.JButton btn_add_leave;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_submit;
    private javax.swing.JComboBox<String> cb_leaveType;
    private com.toedter.calendar.JDateChooser dp_fromDate;
    private com.toedter.calendar.JDateChooser dp_toDate;
    private javax.swing.JLabel emp_name;
    private javax.swing.JLabel icon_salary;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lbl_fetchDOB;
    private javax.swing.JLabel lbl_fetchDepartment;
    private javax.swing.JLabel lbl_fetchEmpID;
    private javax.swing.JLabel lbl_fetchGender;
    private javax.swing.JLabel lbl_fetchMaritalStatus;
    private javax.swing.JLabel lbl_fetchname;
    private javax.swing.JLabel lbl_message;
    private javax.swing.JLabel lbl_profilePicture;
    private javax.swing.JLabel lbl_welcomeEmp;
    private javax.swing.JLabel lbl_welcomeEmployee;
    private javax.swing.JPanel panel_dash;
    private javax.swing.JPanel panel_dashboard;
    private javax.swing.JPanel panel_employees;
    private javax.swing.JPanel panel_leaves;
    private javax.swing.JPanel panel_salary;
    private javax.swing.JPanel panel_settings;
    private javax.swing.JPasswordField pwd_conpass;
    private javax.swing.JPasswordField pwd_newpass;
    private javax.swing.JPanel tab1;
    private javax.swing.JPanel tab2;
    private javax.swing.JPanel tab4;
    private javax.swing.JPanel tab5;
    private javax.swing.JPanel tab6;
    private javax.swing.JTable tbl_leave;
    private javax.swing.JTable tbl_salary;
    private javax.swing.JTextField txtCurrentUserName;
    private javax.swing.JTextArea txt_description;
    // End of variables declaration//GEN-END:variables
}
