/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.employeeManagementSystem.TableActionForDisplayEmployee;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Mydeen
 */
public class ButtonPanelAction extends javax.swing.JPanel {

    /**
     * Creates new form ButtonPanelAction
     */
    public ButtonPanelAction() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_view = new com.employeeManagementSystem.TableActionForDisplayEmployee.ActionButton();
        btn_edit = new com.employeeManagementSystem.TableActionForDisplayEmployee.ActionButton();
        btn_leave = new com.employeeManagementSystem.TableActionForDisplayEmployee.ActionButton();
        btn_delete = new com.employeeManagementSystem.TableActionForDisplayEmployee.ActionButton();

        btn_view.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/employeeManagementSystem/Images/view.png"))); // NOI18N

        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/employeeManagementSystem/Images/edit.png"))); // NOI18N

        btn_leave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/employeeManagementSystem/Images/leave.png"))); // NOI18N

        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/employeeManagementSystem/Images/delete.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_view, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_leave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_leave, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btn_view, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_edit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_delete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void initEvent(TableActionEvent event, int row){
    btn_view.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            event.onView(row);
        }
    });
    
    btn_edit.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            event.onEdit(row);
        }
    });
    
    btn_leave.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            event.onLeave(row); // Assuming this is for leave-related functionality
        }
    });
    
    btn_delete.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            event.onDelete(row); // Updated to call the delete action
        }
    });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.employeeManagementSystem.TableActionForDisplayEmployee.ActionButton btn_delete;
    private com.employeeManagementSystem.TableActionForDisplayEmployee.ActionButton btn_edit;
    private com.employeeManagementSystem.TableActionForDisplayEmployee.ActionButton btn_leave;
    private com.employeeManagementSystem.TableActionForDisplayEmployee.ActionButton btn_view;
    // End of variables declaration//GEN-END:variables
}
